language: node_js
node_js:
- '8'
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk8
script:
  - sonar-scanner -Dsonar.projectKey=ns-expert-advisor -Dsonar.sources=src
  - npm test
cache:
  directories:
    - '$HOME/.sonar/cache'
