language: node_js
node_js:
- '8'
dist: trusty
sudo: required
projectKey: ns-expert-advisor
sources: src
language: js
profile: node

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
